version: '3'

services:
  jphb:
    image: jphb:latest
    container_name: jphb-container
    pull_policy: always
    ports:
      - "80:80"
    volumes:
      - jphb_data:/app/results
      - jphb_projects:/app/projects
    deploy:
      resources:
        limits:
          memory: 16G
    command: ${PROGRAM}
    environment:
      - DOCKER_MEMORY_SWAP=16g
      - PROGRAM